### ISSUE TITLE
api/clips/queue filters out clips that have never been played

### ISSUE THREAD

**Issue by ldesgoui** [IAmThermite/TF2Frags.net#2]
It seems the sort method containing `lastPlayer: 1` makes clips that have never been played come after those who have, making it impossible to play new clips

https://github.com/IAmThermite/TF2Frags.net/blob/master/routes/api.js#L49

**Comment by IAmThermite** [comment]
Last played is actually set to the upload date when the clip is uploaded so will never be undefined. I used to use this as the main sort but it ended up having the clips uploaded in sequence played one after another. It has less of an impact on the order of clips being played now and is mainly just there for display.
